// Web Animations API presets — generated by designlang (motionlang)
// Source: https://www.amplifyaus.org/
// 2026-06-19T01:48:16.950Z
//
// Zero-dependency. Runs on the browser-native Element.animate().
//   import { animations } from './amplifyaus.org-motion.waapi.js';
//   animations.fadeIn(document.querySelector('#hero'));
//   await animations.slideUp(card, { delay: 80 }).finished;

/** Easing curves extracted from the live page, as WAAPI easing strings. */
export const easings = {
  easeOut: 'cubic-bezier(0.19, 1, 0.22, 1)', // 113× on page
  custom2: 'cubic-bezier(0.77, 0, 0.175, 1)', // 8× on page
  custom3: 'cubic-bezier(0.86, 0, 0.07, 1)', // 6× on page
  easeInOut: 'ease', // 4× on page
  linear: 'linear', // 1× on page
  custom7: 'cubic-bezier(0.4, 0, 0.04, 1)', // 1× on page
};

/** Duration presets (milliseconds), extracted from the live page. */
export const durations = {
  xs: 100,
  sm: 200,
  md: 400,
  lg: 600,
  xl: 1000,
  xxl: 1500,
};

/** No on-page @keyframes were attached to elements; emit empty for shape parity. */
export const keyframes = {};

/** Honours the user's reduced-motion preference. */
export const prefersReducedMotion = () =>
  typeof matchMedia === 'function' && matchMedia('(prefers-reduced-motion: reduce)').matches;

const _timing = { duration: 400, easing: easings.easeOut, fill: 'both' };

function _animate(el, frames, opts = {}) {
  const timing = { ..._timing, ...opts };
  if (prefersReducedMotion()) timing.duration = 0;
  return el.animate(frames, timing);
}

/** Animate-on-call helpers. Each returns the live Animation (await `.finished`). */
export const animations = {
  fadeIn: (el, opts = {}) => _animate(el, [{ opacity: 0 }, { opacity: 1 }], opts),
  fadeOut: (el, opts = {}) => _animate(el, [{ opacity: 1 }, { opacity: 0 }], opts),
  slideUp: (el, opts = {}) => _animate(el, [{ opacity: 0, transform: 'translateY(16px)' }, { opacity: 1, transform: 'translateY(0)' }], opts),
  slideDown: (el, opts = {}) => _animate(el, [{ opacity: 0, transform: 'translateY(-16px)' }, { opacity: 1, transform: 'translateY(0)' }], opts),
  scaleIn: (el, opts = {}) => _animate(el, [{ opacity: 0, transform: 'scale(0.96)' }, { opacity: 1, transform: 'scale(1)' }], opts),
};

export default { easings, durations, keyframes, animations, prefersReducedMotion };
