// Auto-generated by designlang. Do not edit by hand.
// Re-extract with `npx designlang <url>` to refresh.
//
// Import next to your token JSON to get type-safe access:
//
//   import type { ColorToken, SpacingToken } from './<host>-tokens';
//   import tokens from './<host>-design-tokens.json';
//
// Source: https://www.amplifyaus.org/
// Generated: 2026-06-19T01:48:16.946Z

export type Hex = `#${string}`;
export type Px  = `${number}px`;
export type Ms  = `${number}ms`;

export type ColorRole = 'primary' | 'secondary' | 'accent';
export type ColorHex  = '#831672' | '#003da2' | '#00530d' | '#000000' | '#00ffe6' | '#ffc7ff' | '#ff8eff' | '#ffffff' | '#00fa7f' | '#ff0580' | '#005768' | '#b42318' | '#ffe3ff' | '#fcdc4d' | '#eeeeee';
export type ColorToken = ColorRole | ColorHex;

export type FontFamilyToken = 'Roboto' | 'Roboto Condensed' | 'Times New Roman';
export type FontSizeToken   = never;
export type FontWeightToken = '500' | '800' | '700' | '400';

export type SpacingToken = '1px' | '37px' | '44px' | '56px' | '64px' | '70px' | '80px' | '93px' | '135px' | '160px' | '240px' | '426px' | '444px';

export type RadiusToken = '6px' | '23px' | '36px' | '44px' | '50px' | '57px' | '82px' | '97px' | '320px' | '1280px' | '15984px';

export type DurationToken = '100ms' | '200ms' | '400ms' | '600ms' | '1000ms' | '1500ms';
export type EasingToken   = never;

export type MaterialLanguage = 'material-you';

export interface DesignTokens {
  color: { [role in ColorRole]: ColorHex };
  typography: {
    family: FontFamilyToken;
    size: FontSizeToken;
    weight: FontWeightToken;
  };
  spacing: ReadonlyArray<SpacingToken>;
  radius:  ReadonlyArray<RadiusToken>;
  motion: {
    duration: ReadonlyArray<DurationToken>;
    easing:   ReadonlyArray<EasingToken>;
  };
}

declare const tokens: DesignTokens;
export default tokens;
