// Framer Motion presets — generated by designlang (motionlang)
// Source: https://www.amplifyaus.org/
// 2026-06-19T01:48:16.948Z
//
//   import { transitions, variants } from './amplifyaus.org-motion.framer';
//   <motion.div variants={variants.slideUp} initial="hidden" animate="show"
//               transition={transitions.base} />

/** Easing curves extracted from the live page, as Framer cubic-bezier arrays. */
export const easings = {
  easeOut: [0.19, 1, 0.22, 1], // 113× on page
  custom2: [0.77, 0, 0.175, 1], // 8× on page
  custom3: [0.86, 0, 0.07, 1], // 6× on page
  easeInOut: [0.25, 0.1, 0.25, 1], // 4× on page
  linear: [0, 0, 1, 1], // 1× on page
  custom7: [0.4, 0, 0.04, 1], // 1× on page
};

/** Duration presets (seconds), extracted from the live page. */
export const durations = {
  xs: 0.1,
  sm: 0.2,
  md: 0.4,
  lg: 0.6,
  xl: 1,
  xxl: 1.5,
};

/** Spring presets — pass to a Framer Motion `transition` prop. */
export const springs = {
  soft: { type: 'spring', stiffness: 320, damping: 30, mass: 1 },
};

/** Ready-to-spread Framer Motion transition objects. */
export const transitions = {
  base:  { duration: 0.4, ease: easings.easeOut },
  fast:  { duration: 0.200, ease: easings.easeOut },
  slow:  { duration: 0.720, ease: easings.easeOut },
  spring: springs.soft,
};

/** Common variants wired to the extracted timing. */
export const variants = {
  fade: {
    hidden: { opacity: 0 },
    show:   { opacity: 1, transition: transitions.base },
  },
  slideUp: {
    hidden: { opacity: 0, y: 16 },
    show:   { opacity: 1, y: 0, transition: transitions.base },
  },
  scaleIn: {
    hidden: { opacity: 0, scale: 0.96 },
    show:   { opacity: 1, scale: 1, transition: transitions.base },
  },
  pop: {
    hidden: { opacity: 0, scale: 0.9 },
    show:   { opacity: 1, scale: 1, transition: springs.soft },
  },
  stagger: {
    hidden: {},
    show:   { transition: { staggerChildren: 0.100 } },
  },
};

/** Site uses scroll- or view-timeline. Drop-in `whileInView` props. */
export const inView = {
  fadeIn: {
    initial: variants.fade.hidden,
    whileInView: variants.fade.show,
    viewport: { once: true, amount: 0.3 },
  },
  riseIn: {
    initial: variants.slideUp.hidden,
    whileInView: variants.slideUp.show,
    viewport: { once: true, amount: 0.3 },
  },
};

export default { easings, durations, springs, transitions, variants, inView };
