// Auto-generated by designlang. Do not edit by hand.
// Re-extract with `npx designlang <url>` to refresh.
//
// Import next to your token JSON to get type-safe access:
//
//   import type { ColorToken, SpacingToken } from './<host>-tokens';
//   import tokens from './<host>-design-tokens.json';
//
// Source: https://community-sweep.vercel.app/
// Generated: 2026-06-19T01:53:06.585Z

export type Hex = `#${string}`;
export type Px  = `${number}px`;
export type Ms  = `${number}ms`;

export type ColorRole = 'primary' | 'secondary' | 'accent';
export type ColorHex  = '#2a2318' | '#ffffff' | '#355a47' | '#5a4e3c' | '#000000' | '#736456' | '#f5f1ea' | '#e4ede8' | '#a85538' | '#4d7a64' | '#ebe3d6' | '#ddd2c2' | '#64170a' | '#b8a48a' | '#c8b190' | '#133220' | '#d4c4ab' | '#c6d8ce';
export type ColorToken = ColorRole | ColorHex;

export type FontFamilyToken = 'Noto Sans TC' | 'Noto Serif TC';
export type FontSizeToken   = never;
export type FontWeightToken = '400' | '600' | '500' | '700';

export type SpacingToken = '2px' | '54px' | '63px' | '72px' | '90px' | '99px' | '108px' | '136px' | '181px' | '208px' | '325px';

export type RadiusToken = '7px' | '14px' | '18px' | '27px' | '32px';

export type DurationToken = '150ms' | '200ms';
export type EasingToken   = never;

export type MaterialLanguage = 'flat';

export interface DesignTokens {
  color: { [role in ColorRole]: ColorHex };
  typography: {
    family: FontFamilyToken;
    size: FontSizeToken;
    weight: FontWeightToken;
  };
  spacing: ReadonlyArray<SpacingToken>;
  radius:  ReadonlyArray<RadiusToken>;
  motion: {
    duration: ReadonlyArray<DurationToken>;
    easing:   ReadonlyArray<EasingToken>;
  };
}

declare const tokens: DesignTokens;
export default tokens;
